services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: clean_architecture_php
    command:
      --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
